# Generated by Django 3.1.6 on 2021-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laws',
            name='law',
            field=models.TextField(max_length=2000),
        ),
    ]
